name: wgx-smoke
on:
  workflow_call:
    inputs:
      repo-type:
        required: true
        type: string
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run smoke task
        run: |
          chmod +x bin/wgx
          chmod +x wgx/cmd/*
          bin/wgx smoke
